# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed98368707b681f6cfffc51dfac14c784a2fbc765136222de1e748af0015f4d59b4eeb76aa655350a71698688b7d6722b2248758eea8befe8ce56e1bf7f45eac

test:
  secret_key_base: 86dee025ef68469e56600615aec4a21cb135ff09813a78e83e787b65ce8f1a0d26e039218b72e017196f844dceb16de35ce883b3b0e1f072e468bb22daa08671

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
